# Generated by Django 3.1.14 on 2023-04-27 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('image', models.ImageField(null=True, upload_to='bike/')),
                ('description', models.TextField()),
                ('price', models.IntegerField(default=0)),
                ('number', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'bike',
            },
        ),
        migrations.CreateModel(
            name='BikeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'db_table': 'bike_category',
            },
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('image', models.ImageField(null=True, upload_to='detail/')),
                ('description', models.TextField()),
                ('price', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'detail',
            },
        ),
        migrations.CreateModel(
            name='DetailCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'detail_category',
            },
        ),
        migrations.CreateModel(
            name='RentOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('delivery_date', models.DateField(null=True)),
                ('bike', models.ManyToManyField(to='bike_rent.Bike')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_order', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rent_order',
            },
        ),
        migrations.CreateModel(
            name='DetailsOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('delivery_date', models.DateTimeField(null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details_order', to=settings.AUTH_USER_MODEL)),
                ('detail', models.ManyToManyField(to='bike_rent.Detail')),
            ],
            options={
                'db_table': 'details_order',
            },
        ),
        migrations.AddField(
            model_name='detail',
            name='category',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bike_rent.detailcategory'),
        ),
        migrations.AddField(
            model_name='bike',
            name='category',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bike_rent.bikecategory'),
        ),
    ]
